exclude = ["themes/**/*"]

[commands.oxfmt]
type = "both"
include = ["**/*.md", "**/*.yml", "**/*.toml"]
cmd = ["oxfmt"]
lint-flags = "--check"
tidy-flags = "--write"
ok-exit-codes = 0
lint-failure-exit-codes = 1

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = ["omegasort", "--sort", "path", "--unique"]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1
ignore-stderr = ["The .+ file is not sorted", "The .+ file is not unique"]

[commands.typos]
type = "lint"
include = "**/*"
cmd = "typos"
invoke = "once"
ok-exit-codes = 0
lint-failure-exit-codes = 2
